improve sys_info_page with command line options

diff --git a/sys_info_page b/sys_info_page
--- a/sys_info_page
+++ b/sys_info_page
@@ -1,12 +1,13 @@
 #!/bin/bash
 
-# Program to output a sysinfo page
+# Program to output a system information page
 
+PROGNAME=$(basename $0)
 TITLE="System Information Report for $HOSTNAME"
 CURRENT_TIME=$(date +"%x %r %z")
 TIMESTAMP="Generated $CURRENT_TIME, by $USER"
 
-report_uptime() {
+report_uptime () {
 
 	cat <<-_EOF_
 		<h2>System Uptime</h2>
@@ -17,7 +18,7 @@ report_uptime() {
 
 }
 
-report_disk_space() {
+report_disk_space () {
 
 	cat <<-_EOF_
 		<h2>Disk Space Utilization</h2>
@@ -28,7 +29,7 @@ report_disk_space() {
 
 }
 
-report_home_space() {
+report_home_space () {
 
 	if [[ $(id -u) -eq 0 ]]; then
 		cat <<-_EOF_
@@ -46,18 +47,97 @@ report_home_space() {
 
 }
 
-cat <<-_EOF_
-	<!DOCTYPE HTML>
-	<html>
-		<head>
-			<title>$TITLE</title>
-		</head>
-		<body>
-			<h1>$TITLE</h1>
-			<p>$TIMESTAMP</p>
-			$(report_uptime)
-			$(report_disk_space)
-			$(report_home_space)
-		</body>
-	</html>
-_EOF_
+usage () {
+
+	echo "$PROGNAME: usage: $PROGNAME [-f file | -i ]"
+	return
+
+}
+
+write_html_page () {
+	cat <<-_EOF_
+		<!DOCTYPE HTML>
+		<html>
+			<head>
+				<title>$TITLE</title>
+			</head>
+			<body>
+				<h1>$TITLE</h1>
+				<p>$TIMESTAMP</p>
+				$(report_uptime)
+				$(report_disk_space)
+				$(report_home_space)
+			</body>
+		</html>
+	_EOF_
+	return
+}
+
+# process command line options
+
+interactive=
+filename=
+
+while [[ -n $1 ]]; do
+
+	case $1 in
+		-f | --file)              shift
+															filename=$1
+															;;
+		-i | --interactive)       interactive=1
+															;;
+		-h | --help)              usage
+															exit
+															;;
+		*)                        usage >&2
+															exit 1
+															;;
+	esac
+	shift
+
+done
+
+# interactive mode
+
+if [[ -n $interactive ]]; then
+
+	while true; do
+
+		read -p "Enter name of output file: " filename
+
+		if [[ -e $filename ]]; then
+
+			read -p "'$filename' exists. Overwrite? [y/n/q] > "
+
+			case $REPLY in
+				Y|y)      break
+									;;
+				Q|q)      echo "Program terminated."
+									exit
+									;;
+				*)        continue
+									;;
+			esac
+
+		elif [[ -z $filename ]]; then
+			continue
+		else
+			break
+		fi
+
+	done
+
+fi
+
+# output HTML page
+
+if [[ -n $filename ]]; then
+	if touch $filename && [[ -f $filename ]]; then
+		write_html_page > $filename
+	else
+		echo "$PROGNAME: Cannot write file '$filename'" >&2
+		exit 1
+	fi
+else
+	write_html_page
+fi
